Repository Piramide-Informatik/iws-manager-webapp, pull requests merged in 2025-07, with the labels that each got.

#453 Employee details
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.html
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.ts
  src/app/modules/employee/components/employee-details/employee-details.component.html
  src/app/modules/employee/components/employee-details/employee-details.component.scss
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.html
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.scss
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.ts
  src/app/modules/employee/employee.module.ts
Labels: feature

#462 QualificationFZ entity created
  package-lock.json
  src/app/Entities/qualificationfz.ts
Labels: enhancement

#489 Employment contract Entity
  src/app/Entities/EmploymentContract.ts
Labels: feature

#492 Update employment contract
  src/app/Services/employment-contract.service.ts
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.html
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.ts
  src/app/modules/employee/components/employee-details/employment-contract-modal/employment-contract-modal.component.html
  src/app/modules/employee/components/employee-details/employment-contract-modal/employment-contract-modal.component.ts
  src/app/modules/employee/utils/employment-contract-utils.ts
  src/app/modules/shared/utils/builders/branch.ts
  src/app/modules/shared/utils/builders/company-type.ts
  src/app/modules/shared/utils/builders/country.ts
  src/app/modules/shared/utils/builders/customer.ts
  src/app/modules/shared/utils/builders/employee.ts
  src/app/modules/shared/utils/builders/salutation.ts
  src/app/modules/shared/utils/builders/state.ts
  src/app/modules/shared/utils/builders/title.ts
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.html
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.ts
  src/app/modules/work-contracts/work-contracts.module.ts
Labels: enhancement

#493 employee form styles
  src/app/modules/employee/components/employee-details/employee-details.component.scss
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.html
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.scss
Labels: enhancement

#496 QualificationFZ service implementation
  src/app/Services/qualificationfz.service.ts
Labels: enhancement

#495 feat(employee-contracts): format contract dates to dd.mm.yy in table view
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.ts
Labels: enhancement

#505 feat: unify column widths for Employment Contracts table and fix Qualification FZ display
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.html
  src/app/modules/master-data/genaral-table/genaral-table.component.scss
  src/styles.scss
Labels: enhancement

#511 fix: date timezone offset issue
  package-lock.json
  package.json
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.ts
  src/app/modules/employee/components/employee-details/employment-contract-modal/employment-contract-modal.component.ts
  src/app/modules/shared/utils/moment-date-utils.ts
Labels: bug

#513 Update contractor
  src/app/modules/contractor/components/contractor-details/contractor-details.component.html
  src/app/modules/contractor/components/contractor-details/contractor-details.component.ts
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.html
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.ts
  src/app/modules/contractor/contractor.module.ts
  src/app/modules/shared/utils/builders/contractor.ts
Labels: enhancement, feature

#515 Double in german format
  src/app/modules/master-data/genaral-table/genaral-table.component.html
  src/app/modules/master-data/genaral-table/genaral-table.component.ts
Labels: enhancement

#516 FIX creating new contact person title
  src/assets/i18n/de.json
Labels: enhancement

#518 Delete arrows from inputs type number
  src/styles.scss
Labels: enhancement

#521 German format in Master Data module
  src/app/modules/employee/components/employee-details/employee-contracts-table/employee-contracts-table.component.ts
  src/app/modules/master-data/genaral-table/genaral-table.component.html
  src/app/modules/master-data/genaral-table/genaral-table.component.ts
  src/app/modules/master-data/master-data.module.ts
Labels: bug

#523 Added common service to display common messages
  src/app/Services/common-messages.service.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/modules/contractor/components/contractor-details/contractor-details.component.ts
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.html
  src/app/modules/customer/components/contact/contact.component.ts
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.ts
  src/app/modules/employee/components/employee-details/employment-contract-modal/employment-contract-modal.component.ts
  src/app/modules/employee/components/employee-overview/employee-overview.component.ts
Labels: feature

#527 message delete employee with contracts
  src/app/Services/common-messages.service.ts
  src/app/general-models/messages.ts
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.ts
  src/app/modules/employee/components/employee-overview/employee-overview.component.ts
  src/app/modules/employee/utils/employee.utils.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#534 occ in employement contracts
  src/app/modules/employee/components/employee-details/employment-contract-modal/employment-contract-modal.component.html
Labels: feature

#528 fix: contractor overview string align left and number align rigth
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.ts
Labels: bug

#573 Feat: Employee Form - hide delete button
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.html
Labels: bug
