Repository Piramide-Informatik/iws-manager-webapp, pull requests merged in 2025-08, with the labels that each got.

#591 Add Subcomponents to Project Allocation
  src/app/Entities/project.ts
  src/app/Entities/subcontract-project.ts
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation-modal/project-allocation-modal.component.html
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation-modal/project-allocation-modal.component.scss
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation-modal/project-allocation-modal.component.ts
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation.component.html
  src/app/modules/subcontracts/subcontracts.module.ts
Labels: duplicate

#597 Feat: update subcontract project
  src/app/Entities/subcontract-project.ts
  src/app/modules/shared/utils/builders/project.ts
  src/app/modules/shared/utils/builders/subcontract-project.ts
  src/app/modules/shared/utils/builders/subcontract-year.ts
  src/app/modules/shared/utils/builders/subcontract.ts
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation-modal/project-allocation-modal.component.ts
Labels: enhancement

#598 feat: Project Allocation Modal- Amount calculation
  src/app/modules/subcontracts/components/subcontracts-detail/project-allocation/project-allocation-modal/project-allocation-modal.component.ts
Labels: enhancement

#668 Feat: update label Employee ID to Employee No in Employment Contract
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug
