Repository Piramide-Informatik/iws-manager-webapp, pull requests merged in 2025-05, with the labels that each got.

#184 Andres/networks
  src/app/modules/master-data/components/networks/components/edit-network/edit-network.component.html
  src/app/modules/master-data/components/networks/components/edit-network/edit-network.component.scss
  src/app/modules/master-data/components/networks/components/edit-network/edit-network.component.spec.ts
  src/app/modules/master-data/components/networks/components/edit-network/edit-network.component.ts
  src/app/modules/master-data/components/networks/networks.component.html
  src/app/modules/master-data/components/networks/networks.component.spec.ts
  src/app/modules/master-data/components/networks/networks.component.ts
  src/app/modules/master-data/genaral-table/genaral-table.component.html
  src/app/modules/master-data/genaral-table/genaral-table.component.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
  src/app/modules/master-data/master-data.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#185 Andres/project status
  src/app/modules/master-data/components/project-status/components/edit-project-status/edit-project-status.component.html
  src/app/modules/master-data/components/project-status/components/edit-project-status/edit-project-status.component.scss
  src/app/modules/master-data/components/project-status/components/edit-project-status/edit-project-status.component.spec.ts
  src/app/modules/master-data/components/project-status/components/edit-project-status/edit-project-status.component.ts
  src/app/modules/master-data/components/project-status/project-status.component.html
  src/app/modules/master-data/components/project-status/project-status.component.spec.ts
  src/app/modules/master-data/components/project-status/project-status.component.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
  src/app/modules/master-data/master-data.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#186 Andres/project funnels
  src/app/modules/master-data/components/project-funnels/components/edit-project-funnel/edit-project-funnel.component.html
  src/app/modules/master-data/components/project-funnels/components/edit-project-funnel/edit-project-funnel.component.scss
  src/app/modules/master-data/components/project-funnels/components/edit-project-funnel/edit-project-funnel.component.spec.ts
  src/app/modules/master-data/components/project-funnels/components/edit-project-funnel/edit-project-funnel.component.ts
  src/app/modules/master-data/components/project-funnels/project-funnels.component.html
  src/app/modules/master-data/components/project-funnels/project-funnels.component.spec.ts
  src/app/modules/master-data/components/project-funnels/project-funnels.component.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
  src/app/modules/master-data/master-data.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#187 Andres/realization probabilities
  src/app/modules/master-data/components/realitation-probabilities/components/edit-realization-probabilities/edit-realization-probabilities.component.html
  src/app/modules/master-data/components/realitation-probabilities/components/edit-realization-probabilities/edit-realization-probabilities.component.scss
  src/app/modules/master-data/components/realitation-probabilities/components/edit-realization-probabilities/edit-realization-probabilities.component.spec.ts
  src/app/modules/master-data/components/realitation-probabilities/components/edit-realization-probabilities/edit-realization-probabilities.component.ts
  src/app/modules/master-data/components/realitation-probabilities/realitation-probabilities.component.html
  src/app/modules/master-data/components/realitation-probabilities/realitation-probabilities.component.spec.ts
  src/app/modules/master-data/components/realitation-probabilities/realitation-probabilities.component.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
  src/app/modules/master-data/master-data.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#188 create billers view
  src/app/modules/master-data/components/billers/billers.component.html
  src/app/modules/master-data/components/billers/billers.component.spec.ts
  src/app/modules/master-data/components/billers/billers.component.ts
  src/app/modules/master-data/components/billers/components/edit-biller/edit-biller.component.html
  src/app/modules/master-data/components/billers/components/edit-biller/edit-biller.component.scss
  src/app/modules/master-data/components/billers/components/edit-biller/edit-biller.component.spec.ts
  src/app/modules/master-data/components/billers/components/edit-biller/edit-biller.component.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
  src/app/modules/master-data/master-data.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#219 fix route to employee detail
  src/app/modules/employee/components/employee-details/employee-details.component.html
  src/app/modules/employee/components/employee-overview/employee-overview.component.html
  src/app/modules/employee/components/employee-overview/employee-overview.component.ts
  src/app/modules/employee/employee.module.ts
Labels: bug

#221 fix route to orders detail
  src/app/modules/orders/components/order-detail/order-details.component.html
  src/app/modules/orders/components/orders-overview/orders-overview.component.html
  src/app/modules/orders/components/orders-overview/orders-overview.component.ts
Labels: bug

#222 fix route to framework agreement detail
  src/app/modules/framework-agreements/components/framework-agreement-details/framework-agreement-details.component.html
  src/app/modules/framework-agreements/components/framework-agreements-summary/framework-agreements-summary.component.html
Labels: bug

#223 fix route to contractor detail
  src/app/modules/contractor/components/contractor-details/contractor-details.component.ts
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.html
  src/app/modules/contractor/components/contractor-overview/contractor-overview.component.ts
Labels: bug

#224 fix route to subcontracts detail
  src/app/modules/subcontracts/components/list-subcontracts/list-subcontracts.component.html
  src/app/modules/subcontracts/components/subcontracts-detail/subcontracts-details.component.html
Labels: bug

#244 Menu fixes
  src/app/app-routing.module.ts
  src/app/core/layout/main-layout/main-layout.component.html
  src/app/core/layout/main-layout/main-layout.component.ts
  src/app/modules/customer/components/list-customers/list-customers.component.html
  src/app/modules/customer/components/page-customer/page-customer.component.html
  src/app/modules/customer/components/page-customer/page-customer.component.spec.ts
  src/app/modules/customer/components/page-customer/page-customer.component.ts
  src/app/modules/customer/components/sub-menu/sub-menu.component.html
  src/app/modules/customer/components/sub-menu/sub-menu.component.scss
  src/app/modules/customer/components/sub-menu/sub-menu.component.ts
  src/app/modules/customer/customer-routing.module.ts
  src/app/modules/customer/customer.module.ts
Labels: enhancement

#268 fix routing employee detail to employee list
  src/app/modules/customer/components/page-customer/page-customer.component.html
  src/app/modules/employee/components/employee-details/employee-details.component.html
  src/app/modules/employee/components/employee-details/employee-details.component.ts
Labels: bug

#269 fix routing contracts orders framework-agreements
  src/app/modules/framework-agreements/components/framework-agreement-details/framework-agreement-details.component.html
  src/app/modules/framework-agreements/components/framework-agreement-details/framework-agreement-details.component.ts
  src/app/modules/orders/components/order-detail/order-details.component.html
  src/app/modules/orders/components/order-detail/order-details.component.ts
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.html
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.ts
Labels: bug

#270 fix routing contractors and subcontracts
  src/app/modules/contractor/components/contractor-details/contractor-details.component.html
  src/app/modules/contractor/components/contractor-details/contractor-details.component.ts
  src/app/modules/subcontracts/components/subcontracts-detail/subcontracts-details.component.html
  src/app/modules/subcontracts/components/subcontracts-detail/subcontracts-details.component.ts
Labels: bug

#279 Fabian/fix address form
  src/app/modules/master-data/components/address/components/edit-salutation/edit-salutation.component.html
  src/app/modules/master-data/components/address/components/edit-salutation/edit-salutation.component.scss
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug

#328 Create Titles Modal and utils
  src/app/modules/master-data/components/title/components/title-form/title-form.component.ts
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.html
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.scss
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.spec.ts
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.ts
  src/app/modules/master-data/components/title/components/title-table/title-table.component.html
  src/app/modules/master-data/components/title/components/title-table/title-table.component.ts
  src/app/modules/master-data/components/title/services/title.service.spec.ts
  src/app/modules/master-data/components/title/services/title.service.ts
  src/app/modules/master-data/components/title/utils/title-utils.ts
  src/app/modules/master-data/master-data.module.ts
Labels: enhancement

#329 New Title: Create a new title
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.ts
  src/app/modules/master-data/components/title/components/title-table/title-table.component.html
  src/app/modules/master-data/master-data.module.ts
Labels: enhancement

#332 Double modal title
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.html
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.scss
  src/app/modules/master-data/components/title/components/title-modal/title-modal.component.ts
  src/app/modules/master-data/components/title/components/title-table/title-table.component.html
  src/app/modules/master-data/components/title/components/title-table/title-table.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#338 Update title form
  src/app/modules/master-data/components/title/components/title-form/title-form.component.html
  src/app/modules/master-data/components/title/components/title-form/title-form.component.ts
  src/app/modules/master-data/components/title/components/title-table/title-table.component.html
  src/app/modules/master-data/components/title/components/title-table/title-table.component.ts
  src/app/modules/master-data/components/title/components/title-table/title.data.ts
  src/app/modules/master-data/components/title/utils/title-state.service.ts
  src/app/modules/master-data/components/title/utils/title-utils.ts
  src/app/modules/master-data/master-data.module.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug, enhancement

#349 Salutation service
  src/app/Entities/salutation.model.ts
  src/app/Entities/salutation.ts
  src/app/Services/salutation.service.ts
  src/app/modules/employee/components/employee-details/employee-details.component.ts
  src/app/modules/master-data/components/address/address.component.ts
  src/app/modules/master-data/components/address/components/address-table/address-table.component.html
  src/app/modules/master-data/components/address/components/address-table/address-table.component.ts
  src/app/modules/master-data/components/salutation/components/edit-salutation/edit-salutation.component.html
  src/app/modules/master-data/components/salutation/components/edit-salutation/edit-salutation.component.scss
  src/app/modules/master-data/components/salutation/components/edit-salutation/edit-salutation.component.spec.ts
  src/app/modules/master-data/components/salutation/components/edit-salutation/edit-salutation.component.ts
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.html
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.scss
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.spec.ts
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.ts
  src/app/modules/master-data/components/salutation/salutation.component.html
  src/app/modules/master-data/components/salutation/salutation.component.spec.ts
  src/app/modules/master-data/components/salutation/salutation.component.ts
  src/app/modules/master-data/components/salutation/utils/salutation.utils.ts
  src/app/modules/master-data/master-data-routing.module.ts
  src/app/modules/master-data/master-data.module.ts
Labels: enhancement

#354 create salutation Form
  src/app/modules/master-data/components/salutation/components/salutation-modal/salutation-modal.component.html
  src/app/modules/master-data/components/salutation/components/salutation-modal/salutation-modal.component.scss
  src/app/modules/master-data/components/salutation/components/salutation-modal/salutation-modal.component.spec.ts
  src/app/modules/master-data/components/salutation/components/salutation-modal/salutation-modal.component.ts
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.html
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.ts
  src/app/modules/master-data/master-data.module.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
  src/environments/environment.ts
Labels: enhancement
