Repository Piramide-Informatik/iws-manager-webapp, pull requests merged in 2025-06, with the labels that each got.

#374 Rename types of company modal
  src/app/modules/master-data/components/types-of-companies/components/company-types-modal/company-types-modal.component.html
  src/app/modules/master-data/components/types-of-companies/components/company-types-modal/company-types-modal.component.scss
  src/app/modules/master-data/components/types-of-companies/components/company-types-modal/company-types-modal.component.spec.ts
  src/app/modules/master-data/components/types-of-companies/components/company-types-modal/company-types-modal.component.ts
  src/app/modules/master-data/components/types-of-companies/components/types-of-companies-table/types-of-companies-table.component.html
  src/app/modules/master-data/components/types-of-companies/components/types-of-companies-table/types-of-companies-table.component.ts
  src/app/modules/master-data/master-data.module.ts
Labels: bug

#377 change style cursor in columns
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/master-data/genaral-table/genaral-table.component.html
Labels: bug

#397 [Fix] Clear contact form when creating new contact in customer detail view
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
Labels: bug

#402 Fixed limits in hoursperweek, maxhoursmonth, maxhoursyear fields for …
  src/app/modules/customer/components/detail-customer/detail-customer.component.html
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
Labels: enhancement

#403 Add new tab functionality for customer table row clicks
  src/app/modules/customer/components/list-customers/list-customers.component.html
  src/app/modules/customer/components/list-customers/list-customers.component.ts
Labels: enhancement

#404 💡 Add multiselect dropdown filter for Company Type column
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/master-data/genaral-table/genaral-table.component.html
Labels: enhancement

#405 Fix: Align customer inputs
  src/app/modules/customer/components/detail-customer/detail-customer.component.html
  src/app/modules/customer/components/detail-customer/detail-customer.component.scss
Labels: bug

#412 feat(customers): implement customer-specific contacts loading
  src/app/Entities/contactPerson.ts
  src/app/Entities/customer.model.ts
  src/app/Entities/customer.ts
  src/app/Entities/salutation.ts
  src/app/Entities/title.ts
  src/app/Services/contact-person.service.ts
  src/app/Services/customer.service.ts
  src/app/Services/salutation.service.ts
  src/app/Services/title.service.ts
  src/app/modules/customer/components/contact/contact.component.ts
  src/app/modules/customer/components/detail-customer/detail-customer.component.html
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/customer/utils/contact-utils.ts
  src/app/modules/customer/utils/customer-utils.ts
  src/app/modules/employee/components/employee-overview/employee-overview.component.ts
  src/app/modules/master-data/components/salutation/components/salutation-table/salutation-table.component.ts
  src/app/modules/master-data/components/salutation/utils/salutation.utils.ts
  src/app/modules/master-data/components/title/components/title-table/title-table.component.ts
Labels: enhancement

#416 feat: Implement dynamic page titles based on route and content
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/master-data/components/countries/countries.component.ts
  src/app/modules/master-data/components/salutation/salutation.component.ts
  src/app/modules/master-data/components/states/states.component.ts
  src/app/modules/master-data/components/title/title.component.ts
  src/app/modules/master-data/components/types-of-companies/types-of-companies.component.ts
  src/app/shared/services/page-title.service.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#419 Fix customer creation route and spinner loading separation
  src/app/modules/customer/components/list-customers/list-customers.component.html
  src/app/modules/customer/components/list-customers/list-customers.component.scss
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/customer/customer-routing.module.ts
  src/app/modules/customer/customer.module.ts
  src/app/modules/customer/utils/customer-utils.ts
Labels: bug, enhancement

#426 Refactor: Use CustomerUtils for Customer Deletion and Improve Error Handling
  src/app/Services/customer.service.ts
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/customer/components/list-customers/list-customers.component.ts
  src/app/modules/customer/utils/customer-utils.ts
Labels: bug

#434 customer versioning
  src/app/Entities/customer.ts
  src/app/Services/customer.service.ts
  src/app/modules/customer/components/detail-customer/detail-customer.component.html
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/customer/utils/customer-utils.ts
Labels: enhancement

#435 translation for updating a contact
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug
