Repository Piramide-Informatik/iws-manager-webapp, pull requests merged in 2025-09, with the labels that each got.

#729 feat: order details sort by fromOrderValue
  src/app/Services/order-commission.service.ts
  src/app/modules/orders/components/order-detail/iws-provision/iws-provision.component.ts
  src/app/modules/orders/utils/order-commission-utils.ts
Labels: enhancement

#747 Fix: EmployeeIWS must accept nulls
  src/app/modules/master-data/components/iws-staff/components/edit-iws-staff/edit-iws-staff.component.ts
  src/app/modules/master-data/components/iws-staff/components/iws-staff-modal/iws-staff-modal.component.ts
Labels: bug

#751 feat: contract details - OCC modal messages updated
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.html
  src/app/modules/work-contracts/components/ContractDetails/contract-details.component.ts
Labels: feature

#752 feat: order details occ error messages updated
  src/app/modules/orders/components/order-detail/order-details.component.html
  src/app/modules/orders/components/order-detail/order-details.component.ts
  src/app/modules/orders/utils/order-utils.ts
Labels: feature

#776 Added functionality to delete Promoter
  src/app/modules/master-data/components/project-funnels/components/modal-project-funnel/modal-project-funnel.component.html
  src/app/modules/master-data/components/project-funnels/components/modal-project-funnel/modal-project-funnel.component.ts
  src/app/modules/master-data/components/project-funnels/project-funnels.component.html
  src/app/modules/master-data/components/project-funnels/project-funnels.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: enhancement

#823 Fix: adjust subcontract delete modal spacing
  src/app/modules/framework-agreements/components/framework-agreements-modal/framework-agreements-modal.component.scss
  src/app/modules/subcontracts/components/subcontract-modal/subcontract-modal.component.scss
Labels: bug

#826 bug: contact person occ - update
  src/app/modules/customer/components/contact/contact.component.html
  src/app/modules/customer/components/contact/contact.component.ts
  src/app/modules/customer/utils/contact-utils.ts
Labels: bug

#838 Fix funding program styles
  src/app/modules/master-data/components/funding-programs/components/funding-program-form/funding-program-form.component.html
  src/app/modules/master-data/components/funding-programs/components/funding-program-form/funding-program-form.component.scss
Labels: bug

#840 Fix new user styles
  src/app/modules/master-data/components/user/components/user-modal/user-modal.component.html
  src/app/modules/master-data/components/user/components/user-modal/user-modal.component.scss
Labels: bug

#844 Fix styles iws teams
  src/app/modules/master-data/components/iws-teams/components/edit-iws-team/edit-iws-team.component.html
  src/app/modules/master-data/components/iws-teams/components/edit-iws-team/edit-iws-team.component.scss
  src/app/modules/master-data/components/iws-teams/components/iws-teams-modal/iws-teams-modal.component.html
  src/app/modules/master-data/components/iws-teams/components/iws-teams-modal/iws-teams-modal.component.scss
Labels: bug

#852 bug: order occ update
  src/app/modules/orders/components/order-detail/order-details.component.ts
  src/app/modules/orders/components/orders-overview/orders-overview.component.html
  src/app/modules/orders/components/orders-overview/orders-overview.component.ts
Labels: bug

#858 bug: framework agreement occ update
  src/app/modules/framework-agreements/components/framework-agreement-details/framework-agreement-details.component.html
  src/app/modules/framework-agreements/components/framework-agreement-details/framework-agreement-details.component.ts
  src/app/modules/framework-agreements/components/framework-agreements-summary/framework-agreements-summary.component.html
  src/app/modules/framework-agreements/components/framework-agreements-summary/framework-agreements-summary.component.ts
Labels: bug

#869 feat: fix qualification overview
  src/app/modules/master-data/components/employee-qualification/components/employee-qualification-table/employee-qualification-table.component.ts
  src/app/modules/master-data/components/employee-qualification/employee-qualification.component.html
  src/app/modules/master-data/genaral-table/genaral-table.component.scss
Labels: feature

#870 bug: Validation on share of day for AbsenceTypes
  src/app/modules/master-data/components/absence-types/components/edit-project-carrier/edit-project-carrier.component.html
  src/app/modules/master-data/components/absence-types/components/edit-project-carrier/edit-project-carrier.component.ts
Labels: bug

#872 fix(subcontract-modal): correct dynamic title for create/delete modes
  src/app/modules/subcontracts/components/list-subcontracts/list-subcontracts.component.html
  src/app/modules/subcontracts/components/list-subcontracts/list-subcontracts.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/i18n/es.json
Labels: bug

#874 feat: security hotspot in sonarcloud
  .github/workflows/sonarcloud.yml
Labels: feature

#878 bug: fit the table in a single view
  src/app/modules/master-data/components/absence-types/absence-types.component.html
  src/app/modules/master-data/components/absence-types/components/edit-project-carrier/edit-project-carrier.component.scss
Labels: bug

#890 Bug: Biller - Change new biller title in german
  src/assets/i18n/de.json
Labels: bug

#899 Translation-fix: SALES TAX title corrected (EN/DE)
  src/app/modules/master-data/components/sales-tax/components/sales-tax-table/sales-tax-table.component.html
  src/app/modules/master-data/components/sales-tax/components/sales-tax-table/sales-tax-table.component.ts
  src/assets/i18n/de.json
Labels: bug

#903 bug: subcontract table width fix
  src/app/modules/subcontracts/components/list-subcontracts/list-subcontracts.component.scss
  src/app/modules/subcontracts/components/list-subcontracts/list-subcontracts.component.ts
Labels: bug

#904 Fix: correct German translation in holidays
  src/app/modules/master-data/components/holidays/components/holiday-modal/holiday-modal.component.scss
  src/assets/i18n/de.json
Labels: bug

#905 Fix: auto-focus cursor on holiday column
  src/app/modules/master-data/components/holidays/components/holidays-table/holidays-table.component.ts
Labels: bug

#907 fix holiday sorted
  src/app/modules/master-data/components/holidays/components/holidays-table/holidays-table.component.ts
Labels: bug

#908 bug: title page customer and employee fix
  src/app/modules/customer/components/detail-customer/detail-customer.component.ts
  src/app/modules/employee/components/employee-details/employee-form/employee-form.component.ts
  src/app/modules/employee/components/employee-overview/employee-overview.component.ts
Labels: bug
